collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6541219
  brandStrength: 1
  lightness: 0.609319
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#26272A'
    - '#A5A6AA'
    - '#F0B365'
  rhythmicContrast: 0
typography_spectrum: 0.9157706
layout_spectrum: 0
name: NVFLSH
