collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.3476703
  lightness: 0.4964158
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#26272A'
    - '#A5A6AA'
    - '#F0B365'
  rhythmicContrast: 1
layout_spectrum: 0.7921147
name: NVFLSH
