collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5143369
  brandStrength: 0.05913978
  lightness: 0.2885305
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#26272A'
    - '#A5A6AA'
    - '#F0B365'
  rhythmicContrast: 0.3405018
typography_spectrum: 0.9157706
layout_spectrum: 0.8315412
name: NVFLSH
